#include "DictIndex.h"

#include <HalStorage.h>
#include <Logging.h>
#include <Memory.h>

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <memory>

namespace {
// Re-opening the idx/dat files on every lookup was the dominant cost of building the Word Lookup
// screen: each SD file open has real filesystem overhead (path resolution, directory traversal),
// and WordLookup::lookup() calls DictIndex::lookupExact() up to 8 window lengths x several
// deinflection candidates x up to 3 dictionaries -- per character position on the page. For a
// full page that's thousands of opens where a handful would do. There are only ever 3 fixed
// (idx, dat) path pairs (jmdict/grammar/jmnedict) for the process's whole lifetime, so it's safe
// to open each pair once (lazily, on first use) and keep it open rather than reopening per call.
// ── Two-tier sparse index (.spx) ────────────────────────────────────────────
// A flat .idx is sorted 40-byte records; a plain binary search over the 600K+ record
// dictionaries costs ~20 scattered SD reads, and Word Lookup does thousands of lookups per
// page -> minutes of SD I/O. The .spx sidecar (generated by scripts/gen_dict_spx.py) is a
// coarse checkpoint layer: one 32-byte headword key per SPX_STRIDE .idx records. We keep a
// RAM sub-sample of those keys (the "coarse" tier, <=MAX_COARSE per dict) and binary-search
// it with ZERO reads to bracket the key into a small on-disk fine window; one read of that
// fine window narrows to a single SPX_STRIDE-record .idx block. Net: ~2 reads instead of ~20.
// Purely additive -- if the .spx is missing or its record count no longer matches the live
// .idx (dict was updated), spxOk stays false and lookupInFile() runs the full binary search.
constexpr uint8_t SPX_MAGIC[8] = {'C', 'P', 'S', 'P', 'X', '1', 0, 0};
constexpr uint32_t SPX_VERSION = 1;
constexpr size_t SPX_HEADER_SIZE = 32;
constexpr size_t SPX_KEY_SIZE = DictIndexRecord::HEADWORD_SIZE;  // 32
// MAX_COARSE balances two costs. Bigger -> more coarse entries in heap during the (memory-tight)
// scan; smaller -> bigger fine windows, and a big fine window is a slow SD read (transfer time,
// not just per-transaction overhead) that the fine-window cache below must then absorb. 128 keeps
// the coarse heap ~10KB (safe headroom under the resident reader) and the fine window ~4KB.
constexpr size_t MAX_COARSE = 128;         // RAM coarse entries per dict
constexpr size_t FINE_SLICE_BYTES = 3904;  // one coarse bracket (>= max cstride*32)

struct CoarseEntry {
  char key[SPX_KEY_SIZE];
  uint32_t fineIdx;  // index into the fine tier this key was sampled from
};

// ALL per-dict cache memory below lives on the HEAP, exact-sized, allocated lazily on first
// lookup and freed by DictIndex::releaseCaches() when the Word Lookup activity exits. It must
// not be static and must not linger: the reader keeps ~180KB resident, and heavy operations
// right after a lookup session (horizontal re-pagination needs a single contiguous 32KB block
// for the zip inflate dictionary) fail if the pool is ~30KB smaller or fragmented by long-lived
// mid-heap allocations. Rebuilding the caches on the next lookup costs only ~0.5s of the scan.

// Diagnostic counters (declared before the spx helpers that touch them). Temporary instrumentation
// for the Word Lookup slowness investigation; see DictIndex::logAndResetStats().
uint32_t g_lookupExactCalls = 0;
uint32_t g_recordCacheHits = 0;
uint32_t g_recordCacheMisses = 0;
uint32_t g_fineReads = 0;  // fine-window SD reads (spx tier)
uint32_t g_fineHits = 0;   // fine-window cache hits (no SD read)

struct DictFileHandles {
  HalFile idxFile;
  HalFile datFile;
  bool opened = false;
  bool triedOpen = false;  // true once an open has been attempted, success or failure

  // Read-ahead cache for the index-record accesses in lookupInFile() (heap; see block comment
  // above). Sized to hold a whole SPX_STRIDE (48) window plus slack, so once the spx has narrowed
  // to a window, a single block fetch serves the window search AND the collect walks. When the
  // allocation failed, readIndexRecord() falls back to direct single-record reads.
  static constexpr size_t BLOCK_RECORDS = 64;
  std::unique_ptr<DictIndexRecord[]> blockCache;
  bool blockCacheTried = false;
  size_t blockStart = SIZE_MAX;  // record index blockCache[0] corresponds to; SIZE_MAX = empty
  size_t blockCount = 0;         // valid records currently in blockCache

  // Sparse-index (.spx) state, populated lazily on first lookup for this dict.
  HalFile spxFile;
  bool spxTried = false;
  bool spxOk = false;
  uint32_t spxStride = 0;
  uint32_t spxFineCount = 0;
  uint32_t spxCStride = 0;
  size_t spxCoarseCount = 0;
  // Coarse tier: one sampled key per spxCStride fine entries, exact-sized (heap).
  std::unique_ptr<CoarseEntry[]> coarse;

  // One-slot cache of the last fine window read for this dict (heap, exact bracket size). A scan
  // position issues ~8 window lengths x several deinflection candidates into the SAME dict, all
  // sharing a leading prefix and thus usually the same coarse bracket -> the same fine window.
  // Caching it turns the per-lookup fine-window read (the dominant cost once the .idx reads are
  // gone) into a RAM hit for most of a position's probes. Per-dict (not shared) so the
  // jmdict/grammar/jmnedict interleaving within one lookupExact() doesn't thrash it.
  std::unique_ptr<uint8_t[]> fineCache;
  size_t fineCacheBytes = 0;          // allocated size (cstride * SPX_KEY_SIZE)
  uint32_t fineCacheLo = UINT32_MAX;  // fine index of fineCache[0]; UINT32_MAX = empty
  size_t fineCacheCount = 0;          // number of 32-byte keys currently cached

  // Free every cache and close every file, returning ALL memory to the pool. Next lookup relearns
  // lazily. Called via DictIndex::releaseCaches() when a Word Lookup activity exits.
  // NOTE: on device, calling ANY HalFile method (including close()) on a never-opened handle is an
  // assert -> panic, and a dict that was never consulted this session (e.g. jmnedict on a page
  // with no kanji/katakana) has never-opened handles -- so every close MUST be isOpen()-guarded.
  void release() {
    if (idxFile.isOpen()) idxFile.close();
    if (datFile.isOpen()) datFile.close();
    if (spxFile.isOpen()) spxFile.close();
    opened = false;
    triedOpen = false;
    blockCache.reset();
    blockCacheTried = false;
    blockStart = SIZE_MAX;
    blockCount = 0;
    spxTried = false;
    spxOk = false;
    coarse.reset();
    fineCache.reset();
    fineCacheBytes = 0;
    fineCacheLo = UINT32_MAX;
    fineCacheCount = 0;
  }
};

DictFileHandles g_jmdictHandles;
DictFileHandles g_grammarHandles;
DictFileHandles g_namesHandles;

DictFileHandles& handlesFor(const char* idxPath) {
  if (std::strcmp(idxPath, DictIndex::GRAMMAR_IDX_PATH) == 0) return g_grammarHandles;
  if (std::strcmp(idxPath, DictIndex::NAMES_IDX_PATH) == 0) return g_namesHandles;
  return g_jmdictHandles;
}

// Derive "/dict/foo.spx" from "/dict/foo.idx" into out (must be >= strlen(idxPath)+1).
// Returns false if idxPath doesn't end in ".idx".
bool spxPathFor(const char* idxPath, char* out, size_t outSize) {
  const size_t len = std::strlen(idxPath);
  if (len < 4 || len + 1 > outSize) return false;
  if (std::memcmp(idxPath + len - 4, ".idx", 4) != 0) return false;
  std::memcpy(out, idxPath, len + 1);
  std::memcpy(out + len - 4, ".spx", 4);
  return true;
}

// Load and validate the .spx sidecar for h, building the RAM coarse tier. Sets h.spxOk.
// Safe to leave spxOk=false on any inconsistency -- lookupInFile() then does a full search.
void loadSpx(DictFileHandles& h, const char* idxPath, size_t recordCount) {
  char spxPath[64];
  if (!spxPathFor(idxPath, spxPath, sizeof(spxPath))) return;
  if (!Storage.openFileForRead("DICT", spxPath, h.spxFile)) return;

  uint8_t header[SPX_HEADER_SIZE];
  if (h.spxFile.read(header, SPX_HEADER_SIZE) != static_cast<int>(SPX_HEADER_SIZE)) return;
  if (std::memcmp(header, SPX_MAGIC, sizeof(SPX_MAGIC)) != 0) return;
  uint32_t version, stride, idxCount, fineCount;
  std::memcpy(&version, header + 8, 4);
  std::memcpy(&stride, header + 12, 4);
  std::memcpy(&idxCount, header + 16, 4);
  std::memcpy(&fineCount, header + 20, 4);
  if (version != SPX_VERSION || stride == 0 || fineCount == 0) return;
  // Stale sidecar (dict file changed) -> fall back to the full search rather than mis-locate.
  if (idxCount != recordCount) {
    LOG_ERR("DICT", "spx %s stale: %u records vs idx %u", spxPath, idxCount, static_cast<unsigned>(recordCount));
    return;
  }

  const uint32_t cstride = (fineCount + MAX_COARSE - 1) / MAX_COARSE;
  // One coarse bracket spans cstride fine entries; that whole slice must fit the scratch buffer.
  if (static_cast<size_t>(cstride) * SPX_KEY_SIZE > FINE_SLICE_BYTES) return;
  const size_t coarseCount = (fineCount + cstride - 1) / cstride;

  auto coarse = makeUniqueNoThrow<CoarseEntry[]>(coarseCount);
  const size_t fineBytes = static_cast<size_t>(cstride) * SPX_KEY_SIZE;
  auto fineCache = makeUniqueNoThrow<uint8_t[]>(fineBytes);
  if (!coarse || !fineCache) {
    // Not enough contiguous heap right now -> stay on the full search. Not fatal.
    LOG_ERR("DICT", "spx alloc failed (%u coarse, %u B fine); using full search", static_cast<unsigned>(coarseCount),
            static_cast<unsigned>(fineBytes));
    return;
  }
  for (size_t c = 0; c < coarseCount; c++) {
    const uint32_t fineIdx = static_cast<uint32_t>(c) * cstride;  // < fineCount by construction
    h.spxFile.seek(SPX_HEADER_SIZE + static_cast<size_t>(fineIdx) * SPX_KEY_SIZE);
    if (h.spxFile.read(reinterpret_cast<uint8_t*>(coarse[c].key), SPX_KEY_SIZE) != static_cast<int>(SPX_KEY_SIZE)) {
      return;  // partial -> leave spxOk false
    }
    coarse[c].fineIdx = fineIdx;
  }

  h.coarse = std::move(coarse);
  h.fineCache = std::move(fineCache);
  h.fineCacheBytes = fineBytes;
  h.fineCacheLo = UINT32_MAX;
  h.fineCacheCount = 0;
  h.spxStride = stride;
  h.spxFineCount = fineCount;
  h.spxCStride = cstride;
  h.spxCoarseCount = coarseCount;
  h.spxOk = true;
  LOG_INF("DICT", "spx %s: %u checkpoints, %u coarse in RAM (%u B)", spxPath, fineCount,
          static_cast<unsigned>(coarseCount), static_cast<unsigned>(coarseCount * sizeof(CoarseEntry)));
}

// Narrow the search to the .idx record window [*lo,*hi) that must contain `key` (a 32-byte,
// null-padded headword) if present. Zero-read coarse RAM search + one fine-window read.
// Returns false (caller keeps [0,recordCount)) on any read error.
bool spxNarrow(DictFileHandles& h, const char* key, size_t recordCount, size_t& lo, size_t& hi) {
  // 1) Coarse RAM binary search: largest ci with coarse[ci].key <= key.
  size_t clo = 0, chi = h.spxCoarseCount;
  while (clo < chi) {
    const size_t mid = clo + (chi - clo) / 2;
    if (std::memcmp(h.coarse[mid].key, key, SPX_KEY_SIZE) <= 0) {
      clo = mid + 1;
    } else {
      chi = mid;
    }
  }
  const size_t ci = (clo > 0) ? clo - 1 : 0;
  const uint32_t fLo = h.coarse[ci].fineIdx;
  const uint32_t fHi = (ci + 1 < h.spxCoarseCount) ? h.coarse[ci + 1].fineIdx : h.spxFineCount;
  const size_t sliceCount = fHi - fLo;
  if (sliceCount == 0 || sliceCount * SPX_KEY_SIZE > h.fineCacheBytes || !h.fineCache) return false;

  // 2) Fetch the fine slice (from the one-slot cache when the coarse bracket is unchanged),
  //    then binary-search it in RAM: largest f with fine[fLo+f] <= key.
  if (h.fineCacheLo != fLo || h.fineCacheCount != sliceCount) {
    g_fineReads++;
    h.spxFile.seek(SPX_HEADER_SIZE + static_cast<size_t>(fLo) * SPX_KEY_SIZE);
    const size_t bytes = sliceCount * SPX_KEY_SIZE;
    if (h.spxFile.read(h.fineCache.get(), bytes) != static_cast<int>(bytes)) {
      h.fineCacheLo = UINT32_MAX;  // invalidate on partial read
      return false;
    }
    h.fineCacheLo = fLo;
    h.fineCacheCount = sliceCount;
  } else {
    g_fineHits++;
  }
  size_t flo = 0, fhi = sliceCount;
  while (flo < fhi) {
    const size_t mid = flo + (fhi - flo) / 2;
    if (std::memcmp(h.fineCache.get() + mid * SPX_KEY_SIZE, key, SPX_KEY_SIZE) <= 0) {
      flo = mid + 1;
    } else {
      fhi = mid;
    }
  }
  const size_t f = fLo + ((flo > 0) ? flo - 1 : 0);
  lo = f * h.spxStride;
  hi = std::min(recordCount, (f + 1) * static_cast<size_t>(h.spxStride));
  return true;
}

// Reads index record `idx` (of `recordCount` total), transparently using/filling h's block cache.
// Semantically identical to a direct seek+read of that one record -- callers don't need to know
// whether this was served from cache or SD.
bool readIndexRecord(DictFileHandles& h, size_t idx, size_t recordCount, DictIndexRecord& out) {
  if (h.blockCache && h.blockStart != SIZE_MAX && idx >= h.blockStart && idx < h.blockStart + h.blockCount) {
    out = h.blockCache[idx - h.blockStart];
    g_recordCacheHits++;
    return true;
  }
  g_recordCacheMisses++;

  if (!h.blockCache && !h.blockCacheTried) {
    h.blockCacheTried = true;
    h.blockCache = makeUniqueNoThrow<DictIndexRecord[]>(DictFileHandles::BLOCK_RECORDS);
  }
  if (!h.blockCache) {
    // No cache memory available -- direct single-record read still works, just slower.
    h.idxFile.seek(idx * sizeof(DictIndexRecord));
    return h.idxFile.read(reinterpret_cast<uint8_t*>(&out), sizeof(DictIndexRecord)) ==
           static_cast<int>(sizeof(DictIndexRecord));
  }

  const size_t half = DictFileHandles::BLOCK_RECORDS / 2;
  const size_t start = (idx > half) ? (idx - half) : 0;
  const size_t count = std::min(DictFileHandles::BLOCK_RECORDS, recordCount - start);

  h.idxFile.seek(start * sizeof(DictIndexRecord));
  const size_t bytesToRead = count * sizeof(DictIndexRecord);
  if (h.idxFile.read(reinterpret_cast<uint8_t*>(h.blockCache.get()), bytesToRead) != static_cast<int>(bytesToRead)) {
    h.blockStart = SIZE_MAX;  // invalidate on read failure -- don't serve a partial block later
    return false;
  }

  h.blockStart = start;
  h.blockCount = count;
  out = h.blockCache[idx - start];
  return true;
}
}  // namespace

bool DictIndex::isAvailable() { return Storage.exists(IDX_PATH) && Storage.exists(DAT_PATH); }

bool DictIndex::lookupInFile(const char* headword, const char* idxPath, const char* datPath, DictEntry& out,
                             bool needDefinition) {
  DictFileHandles& h = handlesFor(idxPath);
  if (!h.opened) {
    // Optional dictionaries (grammar, jmnedict) may genuinely not be on the SD card -- without
    // this latch, every lookup attempt would retry the open (and its filesystem overhead) only to
    // fail again, once per candidate/window/character for the whole page.
    if (h.triedOpen) return false;
    h.triedOpen = true;
    if (!Storage.openFileForRead("DICT", idxPath, h.idxFile) || !Storage.openFileForRead("DICT", datPath, h.datFile)) {
      return false;
    }
    h.opened = true;
  }
  HalFile& idxFile = h.idxFile;
  HalFile& datFile = h.datFile;

  const size_t fileSize = idxFile.size();
  if (fileSize < sizeof(DictIndexRecord)) {
    return false;
  }

  const size_t recordCount = fileSize / sizeof(DictIndexRecord);

  // Build the RAM coarse tier from the .spx sidecar on first use for this dict.
  if (!h.spxTried) {
    h.spxTried = true;
    loadSpx(h, idxPath, recordCount);
  }

  char key[DictIndexRecord::HEADWORD_SIZE];
  std::memset(key, 0, sizeof(key));
  const size_t len = std::strlen(headword);
  if (len >= sizeof(key)) {
    return false;
  }
  std::memcpy(key, headword, len);

  size_t lo = 0;
  size_t hi = recordCount;
  // Narrow the [lo,hi) window with the two-tier sparse index when available -- turns the
  // ~log2(recordCount) scattered reads of the binary search below into a search over a single
  // SPX_STRIDE-record window (served from one block fetch). The window is guaranteed to contain
  // the key if it exists (see scripts/gen_dict_spx.py + its validation), so the backward/forward
  // collect walk below still gathers every same-headword record correctly.
  if (h.spxOk) {
    size_t wlo, whi;
    if (spxNarrow(h, key, recordCount, wlo, whi)) {
      lo = wlo;
      hi = whi;
    }
  }
  DictIndexRecord rec;

  while (lo < hi) {
    const size_t mid = lo + (hi - lo) / 2;
    if (!readIndexRecord(h, mid, recordCount, rec)) {
      break;
    }

    const int cmp = std::memcmp(key, rec.headword, DictIndexRecord::HEADWORD_SIZE);
    if (cmp < 0) {
      hi = mid;
    } else if (cmp > 0) {
      lo = mid + 1;
    } else {
      // Existence-only mode: the caller discards the definition (page scan), so skip the
      // backward walk, the collect walk, and all .dat payload reads -- each is an SD transaction.
      if (!needDefinition) {
        out.headword = headword;
        out.priority = rec.priority;
        out.definition.clear();
        return true;
      }

      // Found a match — scan backwards to find the first record with this headword
      size_t first = mid;
      while (first > 0) {
        DictIndexRecord prevRec;
        if (!readIndexRecord(h, first - 1, recordCount, prevRec)) break;
        if (std::memcmp(key, prevRec.headword, DictIndexRecord::HEADWORD_SIZE) != 0) break;
        first--;
      }

      // Two passes so the highest-priority senses win even when they sit past the first few in
      // storage order. The index groups all same-reading records together but NOT by priority, so
      // a reading with many homophones (ほう: 方/法/報/...袍) could bury the common word (方) behind
      // rarer ones (袍) and the old "read the first 5, then sort those" lost it. Pass 1 walks every
      // sibling reading ONLY the index record (priority + payload location, no .dat read); pass 2
      // reads definitions for just the top-priority few. Pass 1 is cheap index-only SD reads; pass
      // 2 does the same handful of .dat reads as before.
      struct Sib {
        uint8_t priority;
        uint32_t offset;
        uint16_t length;
      };
      constexpr size_t kMaxSiblingScan = 32;  // bound the walk for a pathological reading
      std::vector<Sib> sibs;
      sibs.reserve(kMaxSiblingScan);
      for (size_t idx = first; idx < recordCount && sibs.size() < kMaxSiblingScan; idx++) {
        DictIndexRecord r;
        if (!readIndexRecord(h, idx, recordCount, r)) break;
        if (std::memcmp(key, r.headword, DictIndexRecord::HEADWORD_SIZE) != 0) break;
        sibs.push_back({r.priority, r.offset, r.length});
      }
      if (sibs.empty()) return false;

      // Selection sort by priority (highest first) -- <=32 uint8 compares, negligible.
      for (size_t a = 0; a < sibs.size(); a++) {
        size_t best = a;
        for (size_t b = a + 1; b < sibs.size(); b++)
          if (sibs[b].priority > sibs[best].priority) best = b;
        if (best != a) std::swap(sibs[a], sibs[best]);
      }

      // Read definitions for the top-priority siblings, already in priority order.
      struct Entry {
        std::string def;
        uint8_t priority;
      };
      std::vector<Entry> entries;
      constexpr int kMaxEntries = 5;
      for (size_t s = 0; s < sibs.size() && static_cast<int>(entries.size()) < kMaxEntries; s++) {
        // def.resize() is a bare allocation that abort()s on OOM under -fno-exceptions -- confirmed
        // by a real device crash_report with the heap run down mid-lookup-session. Skip entries
        // that don't comfortably fit (shorter definition instead of a reboot); the size cap also
        // rejects a corrupt/misread record length before it becomes a huge allocation request.
        constexpr uint32_t MAX_DEF_BYTES = 16 * 1024;
        if (sibs[s].length > MAX_DEF_BYTES || ESP.getMaxAllocHeap() < sibs[s].length + 8 * 1024) {
          LOG_ERR("DICT", "Skipping entry (%u bytes, maxAlloc=%u)", static_cast<unsigned>(sibs[s].length),
                  ESP.getMaxAllocHeap());
          if (entries.empty()) continue;  // keep trying: a lower-priority sibling may be smaller
          break;
        }
        datFile.seek(sibs[s].offset);
        std::string def;
        def.resize(sibs[s].length);
        if (datFile.read(reinterpret_cast<uint8_t*>(def.data()), sibs[s].length) != static_cast<int>(sibs[s].length))
          continue;
        entries.push_back({std::move(def), sibs[s].priority});
      }

      if (entries.empty()) return false;

      out.headword = headword;
      out.priority = entries[0].priority;
      if (entries.size() == 1) {
        out.definition = std::move(entries[0].def);
      } else {
        // Merge: show best entry, then separator + other entries. One guarded reserve and
        // plain appends -- the old `a + b` temporary chain doubled the peak allocation, and
        // under a tight heap the merge is droppable (the best entry alone is still useful).
        size_t mergedLen = 0;
        for (const auto& en : entries) mergedLen += en.def.size() + 8;
        if (ESP.getMaxAllocHeap() < mergedLen + 8 * 1024) {
          LOG_ERR("DICT", "Skipping entry merge, heap too low (maxAlloc=%u)", ESP.getMaxAllocHeap());
          out.definition = std::move(entries[0].def);
        } else {
          out.definition.reserve(mergedLen);
          out.definition = entries[0].def;
          for (size_t e = 1; e < entries.size(); e++) {
            out.definition += "\n\n---\n";
            out.definition += entries[e].def;
          }
        }
      }
      return true;
    }
  }

  return false;
}

bool DictIndex::lookupExact(const char* headword, DictEntry& out, uint8_t dictMask, bool needDefinition) {
  g_lookupExactCalls++;
  // No Storage.exists() pre-checks needed here -- lookupInFile()'s own open-once cache already
  // makes a missing optional dictionary (grammar, jmnedict) a cheap no-op after the first attempt,
  // and an existence check would itself be a filesystem call repeated on every lookup otherwise.
  if ((dictMask & DICT_JMDICT) && lookupInFile(headword, IDX_PATH, DAT_PATH, out, needDefinition)) return true;
  if ((dictMask & DICT_GRAMMAR) && lookupInFile(headword, GRAMMAR_IDX_PATH, GRAMMAR_DAT_PATH, out, needDefinition))
    return true;
  if ((dictMask & DICT_NAMES) && lookupInFile(headword, NAMES_IDX_PATH, NAMES_DAT_PATH, out, needDefinition))
    return true;
  return false;
}

void DictIndex::releaseCaches() {
  g_jmdictHandles.release();
  g_grammarHandles.release();
  g_namesHandles.release();
}

void DictIndex::logAndResetStats(const char* label) {
  LOG_INF("DICT", "%s: %u lookupExact, idx %u hits/%u reads, fine %u hits/%u reads (total %u SD reads)", label,
          g_lookupExactCalls, g_recordCacheHits, g_recordCacheMisses, g_fineHits, g_fineReads,
          g_recordCacheMisses + g_fineReads);
  g_lookupExactCalls = 0;
  g_recordCacheHits = 0;
  g_recordCacheMisses = 0;
  g_fineReads = 0;
  g_fineHits = 0;
}
